//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBCPlanningEntities : DbContext
    {
        public MBCPlanningEntities()
            : base("name=MBCPlanningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<constructionStaff> constructionStaffs { get; set; }
        public virtual DbSet<drawingRegister> drawingRegisters { get; set; }
        public virtual DbSet<itemContent> itemContents { get; set; }
        public virtual DbSet<plantHireOrder> plantHireOrders { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<projectRequisition> projectRequisitions { get; set; }
        public virtual DbSet<requisition> requisitions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vendorHQTable> vendorHQTables { get; set; }
        public virtual DbSet<vendorLocationDetail> vendorLocationDetails { get; set; }
    }
}
